---
output: 
  pdf_document:
    latex_engine: pdflatex
    keep_tex: true
    template: C:/Users/model/Box/CV/svmiller_cv_template/svmiller_cv_template.tex
geometry: margin=1in

title: "Curriculum Vitae"
author: Timothy A. Model

jobtitle: "Havighurst Fellow"
address: "Miami University, Oxford, OH"
#address: "1141 W. Olive Ave., Apt. 4, Sunnyvale, CA 94086"
fontawesome: yes
email: tmodel@indiana.edu
github: timothymodel
#phone: "(...) ...-...."
web: timothymodel.com
updated: false

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: Maroon
urlcolor: Maroon
---

# Employment

*Havighurst Fellow* \hfill August 2019--Present \newline
Havighurst Center for Russian and Post-Soviet Studies \hfill \newline
Department of Global and Intercultural Studies \hfill \newline
Miami University, Oxford, OH

# Education

*Ph.D. in Political Science* \hfill July 2019 \newline
Indiana University, Bloomington, IN \hfill \newline
Fields: Comparative Politics \& Quantitative Methods

*B.A. in Diplomacy/Global Politics \& Russian, East European, and Eurasian Studies* \hfill 2012 \newline
Miami University, Oxford, OH

# Research

## Book Project

The Logic of Anti-Corruption Campaigns

## Working Papers

Corruption Intolerance and Protest Mobilization (\emph{under review}) \hfill \newline
Unpacking Anti-Corruption Purges \hfill \newline
The Short and Long-Term Effects of Anti-Corruption Activity on FDI \hfill \newline
The Differential Effects of Anti-Corruption Strategies

## Presentations

American Political Science Association Annual Meeting \hfill 2019, 2018, 2017 \newline
Association for Slavic, East European, \& Eurasian Studies Convention \hfill 2019, 2018 \newline
Moscow HSE-EACES Political Economy Workshop \hfill 2019, 2017 \newline
Midwest Political Science Association Conference \hfill 2018 \newline
Workshop on Urban Activism \& the Development of Civil Society in Russia \hfill 2018 \newline
University of Wisconsin Russia Project Scholar's Workshop \hfill 2018 \newline
Ostrom Workshop Colloquium \hfill 2016 \newline
PSGSA Graduate Student Conference \hfill 2015 \newline
Havighurst Symposium on Putin's Russia \hfill 2011

## Other Publications

Calibration and characterization of intracellular Asante Potassium Green probes, APG-2 and APG-4 (with Priyanka S. Rana, Brandon A. Gibbons, Alexey A. Vereninov, Valentina E. Yurinskaya, Robert J. Clements, and Michael A. Model). *Analytical Biochemistry*. 2018.

## Data Collection

Anti-Corruption Campaign Event Dataset \newline
Moscow Housing Development Survey \& Focus Group Study \newline
Orange Revolution Legacies Survey \newline
Executive Approval Project 

# Fellowships, Grants, \& Awards

## Research and Training

Kennan Institute Title VIII Scholarship \hfill 2018 \newline
Russian Studies Workshop Collaborative Research Fellowship \hfill 2018 \newline
John V. Gillespie Memorial Scholarship \hfill 2018 \newline
Russian Studies Workshop Graduate Research Fellowship \hfill 2018 \newline
Russian Studies Workshop Predissertation Networking Fellowship \hfill 2017 \newline
Ostrom Workshop Graduate Student Research Award \hfill 2016 \newline
Katherine Greenough Fellowship for Best Graduate Student Research Paper \hfill 2016 \newline
Foreign Language and Area Studies Fellowship \hfill 2014 \newline
Department of Political Science Fellowship \hfill 2014 \newline
Mabel LaDuke Lauder Fellowship \hfill 2013 \newline
Havighurst Travel Grant \hfill 2011

## Teaching

Department of Political Science Selection for Lieber Memorial Teaching Award \hfill 2018 \newline
Outstanding Associate Instructor Award \hfill 2017

## Service

Department of Political Science Graduate Leadership Award \hfill 2017

## Conference Travel

HSE-EACES Summer Workshop Travel Grant \hfill 2019 \newline
Graduate and Professional Student Government Travel Award \hfill 2018 \newline
American Political Science Association Meeting Travel Grant \hfill 2018, 2017 \newline
Russian Studies Workshop ASEEES Travel Grant \hfill 2017, 2016 \newline
College of Arts and Sciences Conference Travel Award \hfill 2017 \newline
Department of Poltiical Science Conference Travel Award \hfill 2017 \newline
Center on American Politics Conference Travel Grant \hfill 2017

# Teaching Experience

## Instructor of Record

ITS 201 Introduction to International Studies. Miami University. \hfill Fall 2019 \newline
POLS-Y 200 Politics of Corruption. Indiana University. \hfill Spring 2017 \newline
POLS-Y 205 Analyzing Politics (Research Methods). Indiana University. \hfill Fall 2016

## Teaching Assistant

POLS-Y 205 Analyzing Politics. Indiana University. \hfill Fall 2017, Fall \& Spring 2015, Fall 2014 \newline
POLS-Y 332 Russian Politics. Indiana University. \hfill Spring 2016 \newline
POLS-Y 105 Introduction to Political Theory. Indiana University. \hfill Spring 2016 \newline
POLS-Y 100 American Political Controversies. Indiana University. \hfill Fall 2013

## Teaching Training \& Certifications

Pedagogy Training II. Indiana University. \hfill Fall 2016 \newline
Pedagogy Training I. Indiana University. \hfill Fall 2013--Spring 2014

# Skills \& Qualifications

Programming: \textsf{R}, Python, Stata, JAGS \hfill \newline
Languages: English (native), Russian (professional), Spanish (elementary)

